
//----------------------------------------------------------------------------------

export const FETCH_PRODUCTS_LIST_HAS_ERRORED = "FETCH_PRODUCTS_LIST_HAS_ERRORED";
export const FETCH_PRODUCTS_LIST_IS_LOADING = "FETCH_PRODUCTS_LIST_IS_LOADING";
export const FETCH_PRODUCTS_LIST_SUCCESS = "FETCH_PRODUCTS_LIST_SUCCESS";

export const FETCH_PRODUCT_DETAIL_HAS_ERRORED = "FETCH_PRODUCT_DETAIL_HAS_ERRORED";
export const FETCH_PRODUCT_DETAIL_IS_LOADING = "FETCH_PRODUCT_DETAIL_IS_LOADING";
export const FETCH_PRODUCT_DETAIL_SUCCESS = "FETCH_PRODUCT_DETAIL_SUCCESS";

export const CREATE_PRODUCT_HAS_ERRORED = "CREATE_PRODUCT_HAS_ERRORED";
export const CREATE_PRODUCT_IS_LOADING = "CREATE_PRODUCT_IS_LOADING";

export const UPDATE_PRODUCT_HAS_ERRORED = "UPDATE_PRODUCT_HAS_ERRORED";
export const UPDATE_PRODUCT_IS_LOADING = "UPDATE_PRODUCT_IS_LOADING";



export const FETCH_ASSET_LOOKUP = "FETCH_ASSET_LOOKUP";
